### PR TITLE
Add pset_io

### PR DESCRIPTION
**Pull request by RomanSraj**
Creates an interface to save/load into/from a json file.

- Add pset_io.h
- Add load and write function to pybind_wrapper.cpp

Usage: 
Call _write_pset_to_file_ or _load_pset_from_file_ with the absolute path as argument from your python file to save/load.
e.g. xcs.load_pset_from_file("/home/rome/Documents/pset_0.json")

**Important: When loading a population, make sure there is more than one classifier present!**

### CODE REVIEW

**Comment by rpreen** [comment]
Just some first (very tired) thoughts:

* for saving/loading the entire system state (population set and parameters, etc.) to persistent storage, there already exists the `save()` and `load()` functions, which read/write binary. I think this is the practical way for backing-up and restoring, especially since binary is more compact, and once loaded it can be printed, etc.
* for exporting the population set (but not parameters) to json the `print_pset()` and `json()` functions seem sufficient.
* reading/writing parameters with json is not yet implemented - I'm not sure what the use case is for this (since they will usually be included in the Python script), but I can see it might be useful. This will need quite a few new functions in `param.c`, `ea.c`, etc.
* loading the population set from json is not yet implemented - I can see a potential use case for this being to seed the population with human defined rules, e.g., trees, but maybe this is better as some kind of `insert()` function to manually insert a classifier into the population? This will need lots of new functions as well: basically every current `json()` (writing) function in each condition/action/prediction file will need the equivalent function reading json and a new insert function in `cl.c`, etc.
* importing/exporting the entire system state in json with similar functionality to `save()` and `load()` would need to handle the parameters as well as the population set; but why not just use the binary functions?

**Comment by RomanSraj** [comment]
> Just some first (very tired) thoughts:
> 
> * for saving/loading the entire system state (population set and parameters, etc.) to persistent storage, there already exists the `save()` and `load()` functions, which read/write binary. I think this is the practical way for backing-up and restoring, especially since binary is more compact, and once loaded it can be printed, etc.
> * for exporting the population set (but not parameters) to json the `print_pset()` and `json_export()` functions seem sufficient.
> * reading/writing parameters with json is not yet implemented - I'm not sure what the use case is for this (since they will usually be included in the Python script), but I can see it might be useful [edit: for example, importing parameters in json format could be used to replace the current config reading for standalone execution]. This will need quite a few new functions in `param.c`, `ea.c`, etc.
> * loading the population set from json is not yet implemented - I can see a potential use case for this being to seed the population with human defined rules, e.g., trees, but maybe this is better as some kind of `insert()` function to manually insert a classifier into the population? This will need lots of new functions as well: basically every current `json_export()` function in each condition/action/prediction file will need the equivalent `json_import()` and a new insert function in `cl.c`, etc.
> * importing/exporting the entire system state in json with similar functionality to `save()` and `load()` would need to handle the parameters as well as the population set; but why not just use the binary functions?

Sorry for the (very) late reply. This wasn't actually meant to be added as a PR to your repository, but to a fork of it. We are in need for a json load and save function for our problem and want to see if it has the desired effect on our project. If it works as expected we thought about adding a clean version of it to your repository (in a different PR or the same if you choose to keep this open).

**Comment by rpreen** [comment]
No problem. Having json import functions is something that could be of general use, so if you can send a PR for a clean version that would be great; no pressure though ;-)

**Comment by rpreen** [comment]
Closing this PR since I have just added similar functionality for most types (not GP trees and neural nets yet). See [Seeding the Population](https://github.com/rpreen/xcsf/wiki/Python-Library-Usage#seeding-the-population). If this doesn't meet your needs, it would be great if you could modify it and send a PR for that.

**Pull request closed without merging**
